#!/bin/bash

## check python installed
if ! type "python" > /dev/null; then
  echo "python is not installed"
  exit 1
fi

## check python version
if ! python --version | grep "Python 3.12" > /dev/null; then
  echo "python version is not 3.12"
  exit 1
fi

## check pip installed
if ! type "pip" > /dev/null; then
  echo "pip is not installed"
  exit 1
fi

## install python packages
pip install -r requirements.txt
