#!/bin/bash

## check docker azureupdatepptx image exists
if ! docker images azureupdatepptx | grep azureupdatepptx > /dev/null; then
  echo "docker image azureupdatepptx is not exists"
  exit 1
fi

## display web url
echo "Open http://localhost:8000"

## run docker container
docker run -it -p 8000:8000 azureupdatepptx
