#!/bin/bash

## check docker azureupdatepptx image exists
if ! docker images azureupdatepptx | grep azureupdatepptx > /dev/null; then
  echo "docker image azureupdatepptx is not exists"
  exit 1
fi

LOG_LEVEL_ENV=""

## Check for --debug flag
if [ "$1" = "--debug" ]; then
  echo "Starting container in DEBUG mode..."
  LOG_LEVEL_ENV="--env LOG_LEVEL=debug"
fi

## display web url
echo "Open http://localhost:8000"

## run azureupdatepptx docker container with port 8000
docker run --rm --env-file .env ${LOG_LEVEL_ENV} -d -p 8000:8000 --name azureupdatepptx azureupdatepptx
