#!/bin/bash

## Check streamlit is installed
if ! command -v streamlit > /dev/null; then
  echo "streamlit is not installed"
  exit 1
fi

LOG_LEVEL_OPTION=""

## Check for --debug flag
if [ "$1" = "--debug" ]; then
  echo "Starting server in DEBUG mode..."
  LOG_LEVEL_OPTION="--log_level debug"
fi

## Start the server
exec streamlit run main.py --server.port=8000 --server.enableCORS=false $LOG_LEVEL_OPTION
