#!/bin/bash

## Check streamlit is installed
if ! command -v streamlit > /dev/null; then
  echo "streamlit is not installed"
  exit 1
fi

## Start the server
exec streamlit run main.py --server.port=8000 --server.enableCORS=false
