name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: script/docker-bootstrap
    - name: Set up API_KEY in .env file
      run: echo "API_KEY=fake_key" >> .env
    - name: Set up API_ENDPOINT in .env file
      run: echo "API_ENDPOINT=https://example.com/deployments/test/?api-version=2024-08-01-preview"" >> .env
    - name: Test the Docker image
      run: script/docker-server
    - name: Check http process using curl
      run: |
        sleep 5
        curl -s http://localhost:8000 | grep -q 'Streamlit'
    - name: Stop the Docker image
      run: script/docker-shutdown
