name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: script/docker-bootstrap
    - name: Test the Docker image
      run: script/docker-server
    - name: Check http process using curl
      run: |
        sleep 5
        curl -s http://localhost:8000 | grep -q 'Streamlit'
    - name: Stop the Docker image
      run: script/docker-shutdown
