name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: script/docker-bootstrap
    - name: Set up API_KEY in .env file
      run: echo "API_KEY=fake_key" >> .env
    - name: Set up API_ENDPOINT in .env file
      run: echo "API_ENDPOINT=https://example.com/deployments/test/?api-version=2024-08-01-preview" >> .env
    - name: Test the Docker image
      run: script/docker-server
    - name: Check http process using curl
      run: |
        sleep 5
        curl -s http://localhost:8000 | grep -q 'Streamlit'
    - name: Stop the Docker image
      run: script/docker-shutdown

  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Push to Docker Hub
      run: script/docker-push
    -
      name: Display build summary
      if: success()  # Only show summary if previous steps succeeded
      run: |
        DOCKER_IMAGE=koudaiii/azureupdatepptx
        GIT_COMMIT=$(git rev-parse --short HEAD)
        echo "=== Docker Build & Push Summary ==="
        echo "Repository: $DOCKER_IMAGE"
        echo "Git Commit: $GIT_COMMIT"
        echo "Pushed Tags:"
        echo "  - $DOCKER_IMAGE:$GIT_COMMIT"
        echo "  - $DOCKER_IMAGE:latest"
        echo "Docker Hub URL: https://hub.docker.com/r/koudaiii/azureupdatepptx"
        echo "================================="
